# Generated by Django 5.1 on 2024-09-04 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=1000, editable=False, max_digits=10)),
                ('institution', models.CharField(verbose_name=50)),
                ('bio', models.CharField(verbose_name=200)),
                ('avatar_url', models.FileField(blank=True, editable=False, null=True, upload_to='pfps')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=False)),
                ('dm_notifications', models.BooleanField(default=True)),
                ('forum_answers_notifications', models.BooleanField(default=True)),
                ('private_community_activity_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('DRK', 'Dark'), ('LHT', 'Light')], default='DRK', max_length=3)),
                ('font_size', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(32)])),
                ('language', models.CharField(choices=[('PT-BR', 'Português (Brasil)'), ('EN-US', 'English (US)')], default='PT-BR', max_length=5)),
                ('blocked_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
